### PR TITLE
entregable 2

### PR DESCRIPTION
**Pull request by sanurb**

### CODE REVIEW

**Comment by sanurb** [comment]
The technical documentation is in the gitbook, in the readme you also have the link to the gitbook. 

edit:if there are many changes remember professor that it is because we migrated from a react based template to an angular one and that is why there are so many file changes in the frontend.

**Comment by sebastianlosada** [comment]
LGTM!

**Comment by haroldhenao0** [comment]
LGTM

**Comment by cristiandavidchacon** [comment]
LGTM!!!

**Review by bfmora — APPROVED** [review]

**Pull request merged**
